# used this with codeBuild - builds, tests, and drops zip into an S3 bucket
# also added monitoring with cloudwatch for successful builds, then published email with SNS

version: 0.2

phases:
  pre_build:
    commands:
      - cd lambda/custom && npm install
  build:
    commands:
      - npm test 
  post_build:
    commands:
      - cd ../../
      - mkdir myBuild
      - cp -R lambda myBuild/
      # - cp -R models myBuild/
      - zip theHouse.zip myBuild
      # - tar -zcf theHouse.tar.gz myBuild
      - rm -rf myBuild
artifacts:
  files:
    - theHouse.zip